#!/usr/bin/env bash

if [ -n "$MAKELOVE_VERSION" ]; then
	echo -n "$MAKELOVE_VERSION"
elif git rev-parse --git-dir > /dev/null 2>&1; then
	version=git-$(git rev-parse --short HEAD)-$(git rev-parse --abbrev-ref HEAD)
	! git diff-index --quiet HEAD && version="modified-$version"
	echo -n "$version"
else
	echo -n "unspecified"
fi
